"""creer realtion fans abonnements

Revision ID: bf64332f2596
Revises: c32621f7592e
Create Date: 2024-09-20 18:00:01.334749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf64332f2596'
down_revision = 'c32621f7592e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('abonnes',
    sa.Column('fan_id', sa.Integer(), nullable=False),
    sa.Column('abonnement_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['abonnement_id'], ['utilisateur.id'], ),
    sa.ForeignKeyConstraint(['fan_id'], ['utilisateur.id'], ),
    sa.PrimaryKeyConstraint('fan_id', 'abonnement_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('abonnes')
    # ### end Alembic commands ###
