"""ajouter champs apropos et apercu

Revision ID: c32621f7592e
Revises: 67c275973030
Create Date: 2024-09-20 13:39:45.713529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c32621f7592e'
down_revision = '67c275973030'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('utilisateur', schema=None) as batch_op:
        batch_op.add_column(sa.Column('apropos', sa.String(length=140), nullable=True))
        batch_op.add_column(sa.Column('apercu', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('utilisateur', schema=None) as batch_op:
        batch_op.drop_column('apercu')
        batch_op.drop_column('apropos')

    # ### end Alembic commands ###
